theoremlp/rules_uv

.github/workflows/automation-autosquash.yml
=> Add autosquash

examples/typical/integration_test.sh
examples/typical/integration_test.sh was a hold-over from the setup -- we end up testing uv through the generated tests and the presence of requirements.in/txt.
=> Delete unused file

.github/workflows/periodic-update-multitool.yml
To avoid including the multitool cli as a function of depending on rules_uv, add bespoke automation to get the latest multitool CLI and run it on the uv.lock.json file.
=> Add automation to update uv

.github/workflows/periodic-update-multitool.yml
Errantly included a `-z` (which functions on macos but not on linux)
=> Fix automation for untar'ing xz files on linux

.github/workflows/periodic-update-multitool.yml
rules_uv keeps its lockfile in a non-standard location and our copy/pasted action content didn't update all the usage locations.
Extract the lockfile location to an `env` variable and use that variable everywhere.
=> Use env to refer to a consistent lockfile name in automation

.github/renovate-config.json, .github/renovate.json, .github/reviewers.json, .github/workflows/automation-reviewbot.yml, .github/workflows/periodic-renovate.yml
Add reviewbot and renovate actions to automate approvals of automation PRs and to create automation PRs, respectively. Renovate is configured only to update GitHub actions -- we wish to maintain long backwards compatibility in our MODULE.bazel by using minimum versions.
=> Add reviewbot and renovate automation

.github/workflows/automation-autorelease.yml, .github/workflows/periodic-renovate.yml
Now that rules_uv has automation to update the underlying version of uv, add autorelease automation that will create a tag if there have been commits and at least 7 days since the last release.
=> Add autorelease automation

uv/private/pip_compile.sh, uv/private/pip_compile_test.sh
Better match pip-compile's behavior.
=> Add '--no-strip-extras' to uv pip calls

uv/private/pip.bzl
This can be usefull if the user wants to disable the test
=> fix: Propagate tags to pip-compile rule

.github/workflows/automation-autosquash.yml, .github/workflows/automation-reviewbot.yml
In #23 we had our first external contribution and reviewbot and autosquash automation failed because of secrets access. We don't need either of these to run on external contributions, so limit running them to just the primary repo. Note that autosquash has to have its steps suppressed rather than the task because it's a required action (and needs to be a required action to function).
=> Only run automation steps in the repo

uv/private/pip.bzl
In #23 the tag composition expression resulted in dropping ["requires-network"] when tags are absent.
=> Fix tag composition

uv/private/pip_compile.sh, uv/private/pip_compile_test.sh
... for integration with private registries/indexes
I know that we can also pass `extra_pip_args` in any `pip_parse` repo rules, but this seemed like it might be a nice default behavior to have. I couldn't find any pass discussion of this in the repo.
=> pass --emit-index-url to 'uv pip compile'

.github/workflows/automation-reviewbot.yml
We're trying to get reviewbot not to fail on contributions from a fork -- the prior attempt in #25 didn't seem to do the trick.
=> Suppress reviewbot on individual job items

.bazelrc, examples/typical/.bazelrc, examples/typical/requirements.txt, examples/typical/requirements_linux.txt, uv/private/pip_compile_test.sh
Update `pip_compile_test` to fail on any textual differences in requirements txt output. Prior to this PR, it checked the constraints were satisfied but not that the precise formatting matched. After this PR, any textual output differences will fail the test.
=> Fix pip_compile_test

.github/workflows/automation-reviewbot.yml
In #25 and #34 we've been trying to make it so that reviewbot doesn't fail when submissions come from 3rd party repos. #34 moved the suppression from the job to the step, but we still see a failure in #35 -- reading the failure more closely it seems to be because the secret is absent and the action validator still runs.
Add an alternate value to the reviewbot secret to help pass validation and move the suppression back to the job.
=> Further suppress reviewbot in 3rd party repos

.github/workflows/automation-autosquash.yml, .github/workflows/automation-reviewbot.yml
In #36 (and prior) we were incorrectly using the `repository_owner`, when in fact the docs say we should use the full `repository` key to condition running jobs/steps.
=> Use full name of repository to suppress runs for forks

MODULE.bazel, examples/typical/MODULE.bazel, readme.md
The rules_python maintainers would like to depend on rules_uv to re-publish the `pip_compile` macro, but there's some uncertainty around whether a circular dependency between rules_uv and rules_python would cause problems. rules_uv only depends on there existing a Python toolchain at execution time, and otherwise doesn't need the explicit dependency, so we can remove it.
Remove the rules_python dependency from the main module and add it back in examples. Update the readme to help users continue to have a functioning ruleset.
=> Remove dependency on rules_python

uv/private/pip.bzl, uv/private/pip_compile_test.sh
Follow-up to #35: pass the label of the generator target to the test target explicitly. In #35 we went with a solution that messed with the label string, but passing an explicit label should be safer w/r/t refactors.
=> Pass generator label explicitly

uv/private/uv.lock.json
Some users are running on linux/arm64 and we failed to register a toolchain entry, so they end up with a toolchain failure.
Register a linux/arm64 toolchain.
=> Add a toolchain entry for linux/arm64

uv/private/uv.lock.json
uv no longer produces a gnu-based linux/arm64 build, switch to the statically-compiled-musl build.
=> Switch linux/arm64 binary to static-musl build

uv/private/pip.bzl, uv/private/pip_compile.sh, uv/private/pip_compile_test.sh
Instead of running Python to emit its version, read the Python version from the toolchain in Starlark.
=> Read the Python version from toolchain

readme.md, uv/private/pip.bzl, uv/private/pip_compile.sh, uv/private/pip_compile_test.sh
There's been a lot of interest (see #46 and #53) in supporting custom arguments to be passed to `uv pip compile`, but this is complex because:
- we didn't make it easy to override the defaults
- we pass each argument explicitly from Bazel into the shell script
- we have different scripts for compilation and testing
Use templates to embed arguments directly rather than as bash variables. Refactor `_uv_pip_compile` to allow overriding the default arguments. Document defaults and update the README accordingly.
=> Add support for passing non-default arguments to uv pip compile

.gitignore, examples/typical/BUILD.bazel, uv/private/create_venv.sh, uv/private/venv.bzl
Previously we could pass the directory as an argument when executing the target.
Now it is also possible to set the default destination directory in code.
=> Allow setting venv destination in rule

uv/private/pip.bzl, uv/private/pip_compile.sh, uv/private/pip_compile_test.sh
We were updating PATH to get our desired Python interpreter at the front, but more recent versions of uv let us specify the interpreter explicitly.
Specify the interpreter using `--python` instead of munging the path.
=> Use --python arg instead of PATH munging

uv/private/pip.bzl
This is useful for fields like `exec_properties` with remote exec, and `visibility` to make sure these rules aren't depended on.
=> Pass through kwargs to underlying rules

readme.md, uv/private/pip.bzl
Makes it easier for users to migrate from compile_pip_requirements.
See #96
=> refactor: rename diff_test target to match rules_python

uv/private/pip.bzl
This is a simple way of ensuring $HOME is available for uv to detect `.netrc`.
Fixes #103
=> inherit $HOME environment variable for test

uv/private/pip.bzl
micro version number  is useful when there are some packages that exclude .0 versions due to a bug found in it, such as !=3.11.0 .
See related: https://github.com/plasma-umass/scalene/issues/850
=> add micro version

MODULE.bazel, uv/private/pip.bzl
Could use some help and opinions on the attribute name.
This does add rules_python as a bazel dep in order to use the `PyRuntimeInfo` provider. Not sure if that's undesirable. It seems to make sense since rules_uv already depends on the toolchain made available by it.
Example usage:
```starlark
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
python_version = "3.11",
)
use_repo(
python,
"python_3_11",
)
pip_compile(
name = "requirements_3_11",
py3_runtime = "@python_3_11//:py3_runtime",
requirements_in = "requirements.in",
requirements_txt = "requirements_3_11.txt",
)
```
Fixes #97
=> Enable passing in custom py_runtime

uv/pip.bzl, uv/private/pip.bzl
Allows the underlying rule to have a matching name with the macro.
Demo:
```
alexeagle@aspect-build bazel-examples % bazel print requirements:all
pip_compile(
name = "runtime",
requirements_in = "//:pyproject.toml",
requirements_txt = "runtime.txt",
)
alexeagle@aspect-build bazel-examples % bazel query --output=label_kind requirements:all
pip_compile rule //requirements:runtime
alias rule //requirements:runtime.update
pip_compile_test rule //requirements:runtime_test
```
Fixes #113
=> fix: move pip_compile macro to public API file

uv/private/pip.bzl, uv/private/transition_to_target.bzl, uv/private/venv.bzl
Currently, uv is selected for the exec platform. If it were used as part of a build action, this would be correct, but as it is invoked by an emitted shell script it is not. This causes it to fail when running builds on one platform, but targeting another. This is the case, for example, when running builds in a remote execution cluster with Linux workers, but compiling for a Mac. This patch transitions uv to the proper platform, allowing it to work in this situation.
=> Transition uv to the correct platform

uv/private/create_venv.sh
Prior to this change, `uv venv` wipes out the virtual env target, resulting in longer installations when using private pypi indexes that don't support caching. Adding the `allow-existing` maintains the virtualenv if it exists, and using `uv pip sync`  ensures the virtualenv doesn't retain unused dependencies.
=> Use uv pip sync and allow-existing instead of uv pip install

examples/typical/BUILD.bazel, uv/private/BUILD.bazel, uv/private/sync_venv.sh, uv/private/venv.bzl, uv/venv.bzl
In #166, create_venv was switched to perform a `uv pip sync`, but this has slightly different semantics than `uv pip install`. The latter will expand the input requirements as needed, while the former treats the input as a complete lockfile. To achieve both behaviors, revert `create_venv` to its old functionality and add a `sync_venv` macro that runs `uv pip sync`.
=> Add sync_venv macro

uv/private/create_venv.sh
When using `create_venv` in non-interactive docker container runs, we would get:
```
tput: No value for $TERM and no -T specified
```
This sets `TERM` in case it isn't and enables such runs.
=> Enable create_venv for non-interactive runs

uv/pip.bzl
=> Add test size option

readme.md, uv/pip.bzl, uv/private/pip.bzl
Closes #128
#128 gives a workaround, but it only works when the overrides file is at the root because `args` does not seem to support [Predefined source/output path variables](https://bazel.build/reference/be/make-variables#predefined_label_variables).
This PR makes `requirements_overrides` as a dedicated attr so in the rule can access its `short_path`.
=> feat: Support requirements overrides files

uv/pip.bzl, uv/private/pip.bzl
Closes https://github.com/theoremlp/rules_uv/issues/199
This allows for specifying `extra_args`  which are appended to the default args or overwritten `args`. This way, you can for instance select an extra such as `extra_args = ["--extra=dev-dependencies"]` without having to copy/past the default args.
=> Add extra_args atttribute to append to default args

uv/private/create_venv.sh, uv/private/sync_venv.sh
* bazel creates file write-protected
* using site_packages_extra_files will then cause issues when removing the created venv:
```
rm .venv/lib/python3.12/site-packages/sitecustomize.py
rm: remove write-protected regular file '.venv/lib/python3.12/site-packages/sitecustomize.py'?
```
* this is especially an issue in combination with sync_venv
=> Make venv removeable

MODULE.bazel
This seems to be a clear dev dependency that should not be exposed to the user
=> Make buildifier a dev dependency

.gitattributes, BUILD.bazel, MODULE.bazel, dev/BUILD.bazel
Move buildifier_prebuilt targets into a dev folder and exclude the dev folder from the built artifact. Then, update buildifier_prebuilt to be a dev_dependency.
=> Make buildifier_prebuilt a dev dependency

uv/private/interpreter_path.bzl, uv/private/pip.bzl, uv/private/venv.bzl
When using a local python toolchain as defined [here](https://github.com/bazel-contrib/rules_python/blob/main/docs/toolchains.md#local-toolchain), the `py3_runtime.interpreter` will be set to `None` with the interpreter path accessible via `py3_runtime.interpreter_path`
[Here's](https://github.com/bazel-contrib/rules_python/blob/af9e959538f34878ca0ccccd97d51dc7b3ffdadd/python/private/py_executable.bzl#L1019) an example of code that handles this in rules_python
=> Add support for python toolchains accessible via interpreter_path
